## Exploratory Data Analysis
Exploratory Data Analysis (aka EDA) are a set of techniques typically applied before modeling and can help inform the development of more complex statistical models as well as draw key insights from the data. Exploratory techniques are  important for eliminating or supporting potential hypotheses. Use your newly acquired data slicing skills (Pandas) as well as your knowledge with plotting visualizations (matplotlib, seaborn) to bring your dataset to life.

[IMBD Dataset](https://www.kaggle.com/deepmatrix/imdb-5000-movie-dataset)

**Grading Rubric:**
This homework will be graded by level of effort. Please be sure to draw atleast 3 to 5 conclusions from your EDA process which could potentially support or eliminate a potential hypothesis.

**Submission:**
Please follow the submission guidelines provided [at our student repo](https://github.com/ga-students/DS_DT_13_Students). I will demonstrate a sample homework submissiong during our lecture pertaining to version control.

In [1]:
import pandas as pd
import matplotlib as plt

In [2]:
%time

Wall time: 0 ns

In [3]:
!head -n3 ../datasets/hw1/movie_metadata.csv

'head' is not recognized as an internal or external command,
operable program or batch file.

In [4]:
data = pd.read_csv("../datasets/hw1/movie_metadata.csv")
data

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723,178,0,855,Joel David Moore,1000,760505847,Action|Adventure|Fantasy|Sci-Fi,...,3054,English,USA,PG-13,237000000,2009,936,7.9,1.78,33000
1,Color,Gore Verbinski,302,169,563,1000,Orlando Bloom,40000,309404152,Action|Adventure|Fantasy,...,1238,English,USA,PG-13,300000000,2007,5000,7.1,2.35,0
2,Color,Sam Mendes,602,148,0,161,Rory Kinnear,11000,200074175,Action|Adventure|Thriller,...,994,English,UK,PG-13,245000000,2015,393,6.8,2.35,85000
3,Color,Christopher Nolan,813,164,22000,23000,Christian Bale,27000,448130642,Action|Thriller,...,2701,English,USA,PG-13,250000000,2012,23000,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131,NaN,Rob Walker,131,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12,7.1,NaN,0
5,Color,Andrew Stanton,462,132,475,530,Samantha Morton,640,73058679,Action|Adventure|Sci-Fi,...,738,English,USA,PG-13,263700000,2012,632,6.6,2.35,24000
6,Color,Sam Raimi,392,156,0,4000,James Franco,24000,336530303,Action|Adventure|Romance,...,1902,English,USA,PG-13,258000000,2007,11000,6.2,2.35,0
7,Color,Nathan Greno,324,100,15,284,Donna Murphy,799,200807262,Adventure|Animation|Comedy|Family|Fantasy|Musi...,...,387,English,USA,PG,260000000,2010,553,7.8,1.85,29000
8,Color,Joss Whedon,635,141,0,19000,Robert Downey Jr.,26000,458991599,Action|Adventure|Sci-Fi,...,1117,English,USA,PG-13,250000000,2015,21000,7.5,2.35,118000
9,Color,David Yates,375,153,282,10000,Daniel Radcliffe,25000,301956980,Adventure|Family|Fantasy|Mystery,...,973,English,UK,PG,250000000,2009,11000,7.5,2.35,10000
10,Color,Zack Snyder,673,183,0,2000,Lauren Cohan,15000,330249062,Action|Adventure|Sci-Fi,...,3018,English,USA,PG-13,250000000,2016,4000,6.9,2.35,197000
11,Color,Bryan Singer,434,169,0,903,Marlon Brando,18000,200069408,Action|Adventure|Sci-Fi,...,2367,English,USA,PG-13,209000000,2006,10000,6.1,2.35,0
12,Color,Marc Forster,403,106,395,393,Mathieu Amalric,451,168368427,Action|Adventure,...,1243,English,UK,PG-13,200000000,2008,412,6.7,2.35,0
13,Color,Gore Verbinski,313,151,563,1000,Orlando Bloom,40000,423032628,Action|Adventure|Fantasy,...,1832,English,USA,PG-13,225000000,2006,5000,7.3,2.35,5000
14,Color,Gore Verbinski,450,150,563,1000,Ruth Wilson,40000,89289910,Action|Adventure|Western,...,711,English,USA,PG-13,215000000,2013,2000,6.5,2.35,48000
15,Color,Zack Snyder,733,143,0,748,Christopher Meloni,15000,291021565,Action|Adventure|Fantasy|Sci-Fi,...,2536,English,USA,PG-13,225000000,2013,3000,7.2,2.35,118000
16,Color,Andrew Adamson,258,150,80,201,Pierfrancesco Favino,22000,141614023,Action|Adventure|Family|Fantasy,...,438,English,USA,PG,225000000,2008,216,6.6,2.35,0
17,Color,Joss Whedon,703,173,0,19000,Robert Downey Jr.,26000,623279547,Action|Adventure|Sci-Fi,...,1722,English,USA,PG-13,220000000,2012,21000,8.1,1.85,123000
18,Color,Rob Marshall,448,136,252,1000,Sam Claflin,40000,241063875,Action|Adventure|Fantasy,...,484,English,USA,PG-13,250000000,2011,11000,6.7,2.35,58000
19,Color,Barry Sonnenfeld,451,106,188,718,Michael Stuhlbarg,10000,179020854,Action|Adventure|Comedy|Family|Fantasy|Sci-Fi,...,341,English,USA,PG-13,225000000,2012,816,6.8,1.85,40000
20,Color,Peter Jackson,422,164,0,773,Adam Brown,5000,255108370,Adventure|Fantasy,...,802,English,New Zealand,PG-13,250000000,2014,972,7.5,2.35,65000
21,Color,Marc Webb,599,153,464,963,Andrew Garfield,15000,262030663,Action|Adventure|Fantasy,...,1225,English,USA,PG-13,230000000,2012,10000,7.0,2.35,56000
22,Color,Ridley Scott,343,156,0,738,William Hurt,891,105219735,Action|Adventure|Drama|History,...,546,English,USA,PG-13,200000000,2010,882,6.7,2.35,17000
23,Color,Peter Jackson,509,186,0,773,Adam Brown,5000,258355354,Adventure|Fantasy,...,951,English,USA,PG-13,225000000,2013,972,7.9,2.35,83000
24,Color,Chris Weitz,251,113,129,1000,Eva Green,16000,70083519,Adventure|Family|Fantasy,...,666,English,USA,PG-13,180000000,2007,6000,6.1,2.35,0
25,Color,Peter Jackson,446,201,0,84,Thomas Kretschmann,6000,218051260,Action|Adventure|Drama|Romance,...,2618,English,New Zealand,PG-13,207000000,2005,919,7.2,2.35,0
26,Color,James Cameron,315,194,0,794,Kate Winslet,29000,658672302,Drama|Romance,...,2528,English,USA,PG-13,200000000,1997,14000,7.7,2.35,26000
27,Color,Anthony Russo,516,147,94,11000,Scarlett Johansson,21000,407197282,Action|Adventure|Sci-Fi,...,1022,English,USA,PG-13,250000000,2016,19000,8.2,2.35,72000
28,Color,Peter Berg,377,131,532,627,Alexander Skarsgård,14000,65173160,Action|Adventure|Sci-Fi|Thriller,...,751,English,USA,PG-13,209000000,2012,10000,5.9,2.35,44000
29,Color,Colin Trevorrow,644,124,365,1000,Judy Greer,3000,652177271,Action|Adventure|Sci-Fi|Thriller,...,1290,English,USA,PG-13,150000000,2015,2000,7.0,2.00,150000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5013,Color,Eric Eason,28,79,3,42,Panchito Gómez,93,NaN,Drama|Family,...,21,English,USA,NaN,24000,2002,46,7.0,1.78,61
5014,Color,Uwe Boll,58,80,892,492,Katharine Isabelle,986,NaN,Action|Crime|Thriller,...,129,English,Canada,R,NaN,2009,918,6.3,2.35,0
5015,Black and White,Richard Linklater,61,100,0,0,Richard Linklater,5,1227508,Comedy|Drama,...,80,English,USA,R,23000,1991,0,7.1,1.37,2000
5016,Color,Joseph Mazzella,NaN,90,0,9,Mikaal Bates,313,NaN,Crime|Drama|Thriller,...,2,English,USA,NaN,25000,2015,25,4.8,NaN,33
5017,Color,Travis Legge,1,90,138,138,Suzi Lorraine,370,NaN,Comedy|Romance,...,3,English,USA,NaN,22000,2013,184,3.3,1.78,200
5018,Color,Alex Kendrick,5,120,589,4,Lisa Arnold,51,NaN,Drama,...,49,English,USA,NaN,20000,2003,49,6.9,1.85,725
5019,Color,Marcus Nispel,43,91,158,265,Brittany Curran,630,NaN,Horror|Mystery|Thriller,...,33,English,USA,R,NaN,2015,512,4.6,1.85,0
5020,NaN,Brandon Landers,NaN,143,8,8,Alana Kaniewski,720,NaN,Drama|Horror|Thriller,...,8,English,USA,NaN,17350,2011,19,3.0,NaN,33
5021,Color,Jay Duplass,51,85,157,10,Katie Aselton,830,192467,Comedy|Drama|Romance,...,71,English,USA,R,15000,2005,224,6.6,NaN,297
5022,Black and White,Jim Chuchu,6,60,0,4,Olwenya Maina,147,NaN,Drama,...,1,Swahili,Kenya,NaN,15000,2014,19,7.4,NaN,45
5023,Color,Daryl Wein,22,88,38,211,Heather Burns,331,76382,Romance,...,8,English,USA,NaN,15000,2009,212,6.2,2.35,324
5024,Color,Jason Trost,42,78,91,86,Jason Trost,407,NaN,Sci-Fi|Thriller,...,35,English,USA,Unrated,20000,2011,91,4.0,2.35,835
5025,Color,John Waters,73,108,0,105,Mink Stole,462,180483,Comedy|Crime|Horror,...,183,English,USA,NC-17,10000,1972,143,6.1,1.37,0
5026,Color,Olivier Assayas,81,110,107,45,Béatrice Dalle,576,136007,Drama|Music|Romance,...,39,French,France,R,4500,2004,133,6.9,2.35,171
5027,Color,Jafar Panahi,64,90,397,0,Nargess Mamizadeh,5,673780,Drama,...,26,Persian,Iran,Not Rated,10000,2000,0,7.5,1.85,697
5028,Black and White,Ivan Kavanagh,12,83,18,0,Michael Parle,10,NaN,Horror,...,1,English,Ireland,NaN,10000,2007,5,6.7,1.33,105
5029,Color,Kiyoshi Kurosawa,78,111,62,6,Anna Nakagawa,89,94596,Crime|Horror|Mystery|Thriller,...,50,Japanese,Japan,NaN,1000000,1997,13,7.4,1.85,817
5030,Color,Tadeo Garcia,NaN,84,5,12,Michael Cortez,21,NaN,Drama,...,3,English,USA,NaN,NaN,2004,20,6.1,NaN,22
5031,Color,Thomas L. Phillips,13,82,120,84,Joe Coffey,785,NaN,Comedy|Horror|Thriller,...,8,English,USA,NaN,200000,2012,98,5.4,16.00,424
5032,Color,Ash Baron-Cohen,10,98,3,152,Stanley B. Herman,789,NaN,Crime|Drama,...,14,English,USA,NaN,NaN,1995,194,6.4,NaN,20
5033,Color,Shane Carruth,143,77,291,8,David Sullivan,291,424760,Drama|Sci-Fi|Thriller,...,371,English,USA,PG-13,7000,2004,45,7.0,1.85,19000
5034,Color,Neill Dela Llana,35,80,0,0,Edgar Tancangco,0,70071,Thriller,...,35,English,Philippines,Not Rated,7000,2005,0,6.3,NaN,74
5035,Color,Robert Rodriguez,56,81,0,6,Peter Marquardt,121,2040920,Action|Crime|Drama|Romance|Thriller,...,130,Spanish,USA,R,7000,1992,20,6.9,1.37,0
5036,Color,Anthony Vallone,NaN,84,2,2,John Considine,45,NaN,Crime|Drama,...,1,English,USA,PG-13,3250,2005,44,7.8,NaN,4
5037,Color,Edward Burns,14,95,0,133,Caitlin FitzGerald,296,4584,Comedy|Drama,...,14,English,USA,Not Rated,9000,2011,205,6.4,NaN,413
5038,Color,Scott Smith,1,87,2,318,Daphne Zuniga,637,NaN,Comedy|Drama,...,6,English,Canada,NaN,NaN,2013,470,7.7,NaN,84
5039,Color,NaN,43,43,NaN,319,Valorie Curry,841,NaN,Crime|Drama|Mystery|Thriller,...,359,English,USA,TV-14,NaN,NaN,593,7.5,16.00,32000
5040,Color,Benjamin Roberds,13,76,0,0,Maxwell Moody,0,NaN,Drama|Horror|Thriller,...,3,English,USA,NaN,1400,2013,0,6.3,NaN,16
5041,Color,Daniel Hsia,14,100,0,489,Daniel Henney,946,10443,Comedy|Drama|Romance,...,9,English,USA,PG-13,NaN,2012,719,6.3,2.35,660
5042,Color,Jon Gunn,43,90,16,16,Brian Herzlinger,86,85222,Documentary,...,84,English,USA,PG,1100,2004,23,6.6,1.85,456

In [5]:
data.shape

(5043, 28)

In [6]:
data.head(10)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723,178,0,855,Joel David Moore,1000,760505847,Action|Adventure|Fantasy|Sci-Fi,...,3054,English,USA,PG-13,237000000,2009,936,7.9,1.78,33000
1,Color,Gore Verbinski,302,169,563,1000,Orlando Bloom,40000,309404152,Action|Adventure|Fantasy,...,1238,English,USA,PG-13,300000000,2007,5000,7.1,2.35,0
2,Color,Sam Mendes,602,148,0,161,Rory Kinnear,11000,200074175,Action|Adventure|Thriller,...,994,English,UK,PG-13,245000000,2015,393,6.8,2.35,85000
3,Color,Christopher Nolan,813,164,22000,23000,Christian Bale,27000,448130642,Action|Thriller,...,2701,English,USA,PG-13,250000000,2012,23000,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131,NaN,Rob Walker,131,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12,7.1,NaN,0
5,Color,Andrew Stanton,462,132,475,530,Samantha Morton,640,73058679,Action|Adventure|Sci-Fi,...,738,English,USA,PG-13,263700000,2012,632,6.6,2.35,24000
6,Color,Sam Raimi,392,156,0,4000,James Franco,24000,336530303,Action|Adventure|Romance,...,1902,English,USA,PG-13,258000000,2007,11000,6.2,2.35,0
7,Color,Nathan Greno,324,100,15,284,Donna Murphy,799,200807262,Adventure|Animation|Comedy|Family|Fantasy|Musi...,...,387,English,USA,PG,260000000,2010,553,7.8,1.85,29000
8,Color,Joss Whedon,635,141,0,19000,Robert Downey Jr.,26000,458991599,Action|Adventure|Sci-Fi,...,1117,English,USA,PG-13,250000000,2015,21000,7.5,2.35,118000
9,Color,David Yates,375,153,282,10000,Daniel Radcliffe,25000,301956980,Adventure|Family|Fantasy|Mystery,...,973,English,UK,PG,250000000,2009,11000,7.5,2.35,10000

In [7]:
data.tail(10)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
5033,Color,Shane Carruth,143,77,291,8,David Sullivan,291,424760,Drama|Sci-Fi|Thriller,...,371,English,USA,PG-13,7000,2004,45,7.0,1.85,19000
5034,Color,Neill Dela Llana,35,80,0,0,Edgar Tancangco,0,70071,Thriller,...,35,English,Philippines,Not Rated,7000,2005,0,6.3,NaN,74
5035,Color,Robert Rodriguez,56,81,0,6,Peter Marquardt,121,2040920,Action|Crime|Drama|Romance|Thriller,...,130,Spanish,USA,R,7000,1992,20,6.9,1.37,0
5036,Color,Anthony Vallone,NaN,84,2,2,John Considine,45,NaN,Crime|Drama,...,1,English,USA,PG-13,3250,2005,44,7.8,NaN,4
5037,Color,Edward Burns,14,95,0,133,Caitlin FitzGerald,296,4584,Comedy|Drama,...,14,English,USA,Not Rated,9000,2011,205,6.4,NaN,413
5038,Color,Scott Smith,1,87,2,318,Daphne Zuniga,637,NaN,Comedy|Drama,...,6,English,Canada,NaN,NaN,2013,470,7.7,NaN,84
5039,Color,NaN,43,43,NaN,319,Valorie Curry,841,NaN,Crime|Drama|Mystery|Thriller,...,359,English,USA,TV-14,NaN,NaN,593,7.5,16.00,32000
5040,Color,Benjamin Roberds,13,76,0,0,Maxwell Moody,0,NaN,Drama|Horror|Thriller,...,3,English,USA,NaN,1400,2013,0,6.3,NaN,16
5041,Color,Daniel Hsia,14,100,0,489,Daniel Henney,946,10443,Comedy|Drama|Romance,...,9,English,USA,PG-13,NaN,2012,719,6.3,2.35,660
5042,Color,Jon Gunn,43,90,16,16,Brian Herzlinger,86,85222,Documentary,...,84,English,USA,PG,1100,2004,23,6.6,1.85,456

In [8]:
#Movie Data
#Possible targets could be Profit, Popularity, Critic Ratings, Gross Net, Best Bang For your Buck /Actor/Director/Genre/

In [9]:
#clean up the data

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5043 entries, 0 to 5042
Data columns (total 28 columns):
color                        5024 non-null object
director_name                4939 non-null object
num_critic_for_reviews       4993 non-null float64
duration                     5028 non-null float64
director_facebook_likes      4939 non-null float64
actor_3_facebook_likes       5020 non-null float64
actor_2_name                 5030 non-null object
actor_1_facebook_likes       5036 non-null float64
gross                        4159 non-null float64
genres                       5043 non-null object
actor_1_name                 5036 non-null object
movie_title                  5043 non-null object
num_voted_users              5043 non-null int64
cast_total_facebook_likes    5043 non-null int64
actor_3_name                 5020 non-null object
facenumber_in_poster         5030 non-null float64
plot_keywords                4890 non-null object
movie_imdb_link              5043 non-null object
num_user_for_reviews         5022 non-null float64
language                     5031 non-null object
country                      5038 non-null object
content_rating               4740 non-null object
budget                       4551 non-null float64
title_year                   4935 non-null float64
actor_2_facebook_likes       5030 non-null float64
imdb_score                   5043 non-null float64
aspect_ratio                 4714 non-null float64
movie_facebook_likes         5043 non-null int64
dtypes: float64(13), int64(3), object(12)
memory usage: 1.1+ MB

In [11]:
data.genres

0                         Action|Adventure|Fantasy|Sci-Fi
1                                Action|Adventure|Fantasy
2                               Action|Adventure|Thriller
3                                         Action|Thriller
4                                             Documentary
5                                 Action|Adventure|Sci-Fi
6                                Action|Adventure|Romance
7       Adventure|Animation|Comedy|Family|Fantasy|Musi...
8                                 Action|Adventure|Sci-Fi
9                        Adventure|Family|Fantasy|Mystery
10                                Action|Adventure|Sci-Fi
11                                Action|Adventure|Sci-Fi
12                                       Action|Adventure
13                               Action|Adventure|Fantasy
14                               Action|Adventure|Western
15                        Action|Adventure|Fantasy|Sci-Fi
16                        Action|Adventure|Family|Fantasy
17                                Action|Adventure|Sci-Fi
18                               Action|Adventure|Fantasy
19          Action|Adventure|Comedy|Family|Fantasy|Sci-Fi
20                                      Adventure|Fantasy
21                               Action|Adventure|Fantasy
22                         Action|Adventure|Drama|History
23                                      Adventure|Fantasy
24                               Adventure|Family|Fantasy
25                         Action|Adventure|Drama|Romance
26                                          Drama|Romance
27                                Action|Adventure|Sci-Fi
28                       Action|Adventure|Sci-Fi|Thriller
29                       Action|Adventure|Sci-Fi|Thriller
                              ...
5013                                         Drama|Family
5014                                Action|Crime|Thriller
5015                                         Comedy|Drama
5016                                 Crime|Drama|Thriller
5017                                       Comedy|Romance
5018                                                Drama
5019                              Horror|Mystery|Thriller
5020                                Drama|Horror|Thriller
5021                                 Comedy|Drama|Romance
5022                                                Drama
5023                                              Romance
5024                                      Sci-Fi|Thriller
5025                                  Comedy|Crime|Horror
5026                                  Drama|Music|Romance
5027                                                Drama
5028                                               Horror
5029                        Crime|Horror|Mystery|Thriller
5030                                                Drama
5031                               Comedy|Horror|Thriller
5032                                          Crime|Drama
5033                                Drama|Sci-Fi|Thriller
5034                                             Thriller
5035                  Action|Crime|Drama|Romance|Thriller
5036                                          Crime|Drama
5037                                         Comedy|Drama
5038                                         Comedy|Drama
5039                         Crime|Drama|Mystery|Thriller
5040                                Drama|Horror|Thriller
5041                                 Comedy|Drama|Romance
5042                                          Documentary
Name: genres, dtype: object

In [12]:
genres_type = pd.read_table("../datasets/hw1/movie_metadata.csv"}

SyntaxError: invalid syntax (<ipython-input-12-72589a2ffadb>, line 1)

In [ ]:
Sci_fi = 0  # counters for the genres
Crime = 0
Drama = 0
Comedy = 0 
Horror = 0
Thriller = 0
Docum = 0
Myst = 0
Action = 0
Adven = 0
Roma = 0
Hist = 0
Fam = 0
Fan = 0
Music = 0
Ani = 0
West = 0
War = 0
Bio = 0
Known = 0
Knowncheck = 0
Unknown = 0 # see if we have all the genres listed
All_genres = "Sci-Fi","Crime","Drama","Comedy","Horror","Thriller","Mystery","Documentary","Action","Adventure","Romance","History","Family","Fantasy","Music","Animation","Western","War","Biography"
Counter = len(data.genres)

for n in data.genres: # starting the process of seperating the data
        if "Sci-Fi" in n:
            Sci_fi += 1
            Known += 1
            #print n  used to get a cursory glance to see if i was missing anything
        if "Crime" in n:
            Crime += 1
            Known += 1
            #print n  used to get a cursory glance to see if i was missing anything
        if "Drama" in n:
            Drama += 1
            Known += 1
            #print n  used to get a cursory glance to see if i was missing anything
        if "Comedy" in n:
            Comedy += 1
            Known += 1
            #print n  used to get a cursory glance to see if i was missing anything
        if "Horror" in n:
            Horror += 1
            Known += 1
            #print n  used to get a cursory glance to see if i was missing anything
        if "Thriller" in n:
            Thriller += 1
            Known += 1
            #print n  used to get a cursory glance to see if i was missing anything
        if "Documentary" in n:
            Docum += 1
            Known += 1
            #print n  used to get a cursory glance to see if i was missing anything
        if "Mystery" in n:
            Myst += 1
            Known += 1
            #print n  used to get a cursory glance to see if i was missing anything
        if "Action" in n:
            Action += 1
            Known += 1
            #print n
        if "Adventure" in n:
            Adven += 1
            Known += 1
            #print n  used to get a cursory glance to see if i was missing anything
        if "Romance" in n:
            Roma += 1
            Known += 1
            #print n  used to get a cursory glance to see if i was missing anything
        if "History" in n:
            Hist += 1
            Known += 1
            #print n  used to get a cursory glance to see if i was missing anything
        if "Family" in n:
            Fam += 1
            Known += 1
            #print n  used to get a cursory glance to see if i was missing anything
        if "Fantasy" in n:
            Fan += 1
            Known += 1
            #print n  used to get a cursory glance to see if i was missing anything
        if "Music" in n:
            Music += 1
            Known += 1
            print n  #used to get a cursory glance to see if i was missing anything
        if "Musical" in n:
            Musical += 1
            
        if "Animation" in n:
            Ani += 1
            Known += 1
            #print n  used to get a cursory glance to see if i was missing anything
        if "Western" in n:
            West += 1
            Known += 1
            #print n  used to get a cursory glance to see if i was missing anything
        if "War" in n:
            War += 1
            Known += 1
            #print n  
        if "Biography" in n:
            Bio += 1
            Known += 1
            #print n  used to get a cursory glance to see if i was missing anything
        if any(c in n for c in All_genres):  
            Knowncheck += 1
        else:
            Unknown += 1
        
print Knowncheck

In [ ]:
elif any(c in n for c in All_genres): 
            Counter -= 1
            print Counter
            if ("Sci-Fi" or "Crime" or "Drama" or "Comedy" or "Horror" or "Thriller" or "Documentary" or "Mystery" or "Action" 
        or "Adventure" or "Romance" or "History" or "Family" or "Fantasy" or "Music" or "Animation" or "Western"
        or "War" or "Biography") not in n:

In [13]:
data.describe()

,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,gross,num_voted_users,cast_total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
count,4993.000000,5028.000000,4939.000000,5020.000000,5036.000000,4.159000e+03,5043.000000,5043.000000,5030.000000,5022.000000,4.551000e+03,4935.000000,5030.000000,5043.000000,4714.000000,5043.000000
mean,140.194272,107.201074,686.509212,645.009761,6560.047061,4.846841e+07,83668.160817,9699.063851,1.371173,272.770808,3.975262e+07,2002.470517,1651.754473,6.442138,2.220403,7525.964505
std,121.601675,25.197441,2813.328607,1665.041728,15020.759120,6.845299e+07,138485.256806,18163.799124,2.013576,377.982886,2.061149e+08,12.474599,4042.438863,1.125116,1.385113,19320.445110
min,1.000000,7.000000,0.000000,0.000000,0.000000,1.620000e+02,5.000000,0.000000,0.000000,1.000000,2.180000e+02,1916.000000,0.000000,1.600000,1.180000,0.000000
25%,50.000000,93.000000,7.000000,133.000000,614.000000,5.340988e+06,8593.500000,1411.000000,0.000000,65.000000,6.000000e+06,1999.000000,281.000000,5.800000,1.850000,0.000000
50%,110.000000,103.000000,49.000000,371.500000,988.000000,2.551750e+07,34359.000000,3090.000000,1.000000,156.000000,2.000000e+07,2005.000000,595.000000,6.600000,2.350000,166.000000
75%,195.000000,118.000000,194.500000,636.000000,11000.000000,6.230944e+07,96309.000000,13756.500000,2.000000,326.000000,4.500000e+07,2011.000000,918.000000,7.200000,2.350000,3000.000000
max,813.000000,511.000000,23000.000000,23000.000000,640000.000000,7.605058e+08,1689764.000000,656730.000000,43.000000,5060.000000,1.221550e+10,2016.000000,137000.000000,9.500000,16.000000,349000.000000

In [14]:
data.isnull().sum() # looking for similarities in nulls

color                         19
director_name                104
num_critic_for_reviews        50
duration                      15
director_facebook_likes      104
actor_3_facebook_likes        23
actor_2_name                  13
actor_1_facebook_likes         7
gross                        884
genres                         0
actor_1_name                   7
movie_title                    0
num_voted_users                0
cast_total_facebook_likes      0
actor_3_name                  23
facenumber_in_poster          13
plot_keywords                153
movie_imdb_link                0
num_user_for_reviews          21
language                      12
country                        5
content_rating               303
budget                       492
title_year                   108
actor_2_facebook_likes        13
imdb_score                     0
aspect_ratio                 329
movie_facebook_likes           0
dtype: int64

In [15]:
data.gross.describe()

count    4.159000e+03
mean     4.846841e+07
std      6.845299e+07
min      1.620000e+02
25%      5.340988e+06
50%      2.551750e+07
75%      6.230944e+07
max      7.605058e+08
Name: gross, dtype: float64

In [16]:
data[data.gross > 300000000].director_name

0           James Cameron
1          Gore Verbinski
3       Christopher Nolan
6               Sam Raimi
8             Joss Whedon
9             David Yates
10            Zack Snyder
13         Gore Verbinski
17            Joss Whedon
26          James Cameron
27          Anthony Russo
29        Colin Trevorrow
30             Sam Mendes
31              Sam Raimi
32            Shane Black
33             Tim Burton
36            Michael Bay
43            Lee Unkrich
45              James Wan
53            Michael Bay
54       Steven Spielberg
66      Christopher Nolan
69            Jon Favreau
78            Pete Docter
79            Jon Favreau
80            Jon Favreau
95             James Gunn
99          Peter Jackson
107          Chris Miller
112           Michael Bay
              ...
202        Chris Columbus
205        Gore Verbinski
207      Francis Lawrence
236          George Lucas
237          George Lucas
240          George Lucas
270         Peter Jackson
338        Andrew Stanton
339         Peter Jackson
340         Peter Jackson
439             Gary Ross
509          Roger Allers
519         Yarrow Cheney
521         Pierre Coffin
522       Roland Emmerich
563            Kyle Balda
582        Andrew Adamson
631           David Slade
697      Steven Spielberg
794           Joss Whedon
812            Tim Miller
814        Clint Eastwood
836       Robert Zemeckis
1536     Richard Marquand
1805          Jon Favreau
3024         George Lucas
3080     Steven Spielberg
3461            Sam Raimi
3493           Sam Mendes
4128           Tim Burton
Name: director_name, dtype: object

In [17]:
(data.gross.isnull() & data.budget.isnull()).sum() # checking to see if there is direct connection between null gross and null budget

224

In [18]:
data.budget.dropna()  #the budgets of the movies with na removed

0       237000000
1       300000000
2       245000000
3       250000000
5       263700000
6       258000000
7       260000000
8       250000000
9       250000000
10      250000000
11      209000000
12      200000000
13      225000000
14      215000000
15      225000000
16      225000000
17      220000000
18      250000000
19      225000000
20      250000000
21      230000000
22      200000000
23      225000000
24      180000000
25      207000000
26      200000000
27      250000000
28      209000000
29      150000000
30      200000000
          ...
5002        50000
5004        30000
5006        60000
5008       230000
5009        27000
5011        25000
5012     35000000
5013        24000
5015        23000
5016        25000
5017        22000
5018        20000
5020        17350
5021        15000
5022        15000
5023        15000
5024        20000
5025        10000
5026         4500
5027        10000
5028        10000
5029      1000000
5031       200000
5033         7000
5034         7000
5035         7000
5036         3250
5037         9000
5040         1400
5042         1100
Name: budget, dtype: float64

In [19]:
data.gross.dropna()-data.budget.dropna()

0       523505847
1         9404152
2       -44925825
3       198130642
5      -190641321
6        78530303
7       -59192738
8       208991599
9        51956980
10       80249062
11       -8930592
12      -31631573
13      198032628
14     -125710090
15       66021565
16      -83385977
17      403279547
18       -8936125
19      -45979146
20        5108370
21       32030663
22      -94780265
23       33355354
24     -109916481
25       11051260
26      458672302
27      157197282
28     -143826840
29      502177271
30      104360277
          ...
5006          NaN
5007          NaN
5008      2921130
5009       -18769
5011      2831622
5012    -24500032
5013          NaN
5015      1204508
5016          NaN
5017          NaN
5018          NaN
5020          NaN
5021       177467
5022          NaN
5023        61382
5024          NaN
5025       170483
5026       131507
5027       663780
5028          NaN
5029      -905404
5031          NaN
5033       417760
5034        63071
5035      2033920
5036          NaN
5037        -4416
5040          NaN
5041          NaN
5042        84122
dtype: float64

In [20]:
 
data['profit'] = data.gross-data.budget # add a column for profit

In [21]:
data    #tada there is profit!

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,profit
0,Color,James Cameron,723,178,0,855,Joel David Moore,1000,760505847,Action|Adventure|Fantasy|Sci-Fi,...,English,USA,PG-13,237000000,2009,936,7.9,1.78,33000,523505847
1,Color,Gore Verbinski,302,169,563,1000,Orlando Bloom,40000,309404152,Action|Adventure|Fantasy,...,English,USA,PG-13,300000000,2007,5000,7.1,2.35,0,9404152
2,Color,Sam Mendes,602,148,0,161,Rory Kinnear,11000,200074175,Action|Adventure|Thriller,...,English,UK,PG-13,245000000,2015,393,6.8,2.35,85000,-44925825
3,Color,Christopher Nolan,813,164,22000,23000,Christian Bale,27000,448130642,Action|Thriller,...,English,USA,PG-13,250000000,2012,23000,8.5,2.35,164000,198130642
4,NaN,Doug Walker,NaN,NaN,131,NaN,Rob Walker,131,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,12,7.1,NaN,0,NaN
5,Color,Andrew Stanton,462,132,475,530,Samantha Morton,640,73058679,Action|Adventure|Sci-Fi,...,English,USA,PG-13,263700000,2012,632,6.6,2.35,24000,-190641321
6,Color,Sam Raimi,392,156,0,4000,James Franco,24000,336530303,Action|Adventure|Romance,...,English,USA,PG-13,258000000,2007,11000,6.2,2.35,0,78530303
7,Color,Nathan Greno,324,100,15,284,Donna Murphy,799,200807262,Adventure|Animation|Comedy|Family|Fantasy|Musi...,...,English,USA,PG,260000000,2010,553,7.8,1.85,29000,-59192738
8,Color,Joss Whedon,635,141,0,19000,Robert Downey Jr.,26000,458991599,Action|Adventure|Sci-Fi,...,English,USA,PG-13,250000000,2015,21000,7.5,2.35,118000,208991599
9,Color,David Yates,375,153,282,10000,Daniel Radcliffe,25000,301956980,Adventure|Family|Fantasy|Mystery,...,English,UK,PG,250000000,2009,11000,7.5,2.35,10000,51956980
10,Color,Zack Snyder,673,183,0,2000,Lauren Cohan,15000,330249062,Action|Adventure|Sci-Fi,...,English,USA,PG-13,250000000,2016,4000,6.9,2.35,197000,80249062
11,Color,Bryan Singer,434,169,0,903,Marlon Brando,18000,200069408,Action|Adventure|Sci-Fi,...,English,USA,PG-13,209000000,2006,10000,6.1,2.35,0,-8930592
12,Color,Marc Forster,403,106,395,393,Mathieu Amalric,451,168368427,Action|Adventure,...,English,UK,PG-13,200000000,2008,412,6.7,2.35,0,-31631573
13,Color,Gore Verbinski,313,151,563,1000,Orlando Bloom,40000,423032628,Action|Adventure|Fantasy,...,English,USA,PG-13,225000000,2006,5000,7.3,2.35,5000,198032628
14,Color,Gore Verbinski,450,150,563,1000,Ruth Wilson,40000,89289910,Action|Adventure|Western,...,English,USA,PG-13,215000000,2013,2000,6.5,2.35,48000,-125710090
15,Color,Zack Snyder,733,143,0,748,Christopher Meloni,15000,291021565,Action|Adventure|Fantasy|Sci-Fi,...,English,USA,PG-13,225000000,2013,3000,7.2,2.35,118000,66021565
16,Color,Andrew Adamson,258,150,80,201,Pierfrancesco Favino,22000,141614023,Action|Adventure|Family|Fantasy,...,English,USA,PG,225000000,2008,216,6.6,2.35,0,-83385977
17,Color,Joss Whedon,703,173,0,19000,Robert Downey Jr.,26000,623279547,Action|Adventure|Sci-Fi,...,English,USA,PG-13,220000000,2012,21000,8.1,1.85,123000,403279547
18,Color,Rob Marshall,448,136,252,1000,Sam Claflin,40000,241063875,Action|Adventure|Fantasy,...,English,USA,PG-13,250000000,2011,11000,6.7,2.35,58000,-8936125
19,Color,Barry Sonnenfeld,451,106,188,718,Michael Stuhlbarg,10000,179020854,Action|Adventure|Comedy|Family|Fantasy|Sci-Fi,...,English,USA,PG-13,225000000,2012,816,6.8,1.85,40000,-45979146
20,Color,Peter Jackson,422,164,0,773,Adam Brown,5000,255108370,Adventure|Fantasy,...,English,New Zealand,PG-13,250000000,2014,972,7.5,2.35,65000,5108370
21,Color,Marc Webb,599,153,464,963,Andrew Garfield,15000,262030663,Action|Adventure|Fantasy,...,English,USA,PG-13,230000000,2012,10000,7.0,2.35,56000,32030663
22,Color,Ridley Scott,343,156,0,738,William Hurt,891,105219735,Action|Adventure|Drama|History,...,English,USA,PG-13,200000000,2010,882,6.7,2.35,17000,-94780265
23,Color,Peter Jackson,509,186,0,773,Adam Brown,5000,258355354,Adventure|Fantasy,...,English,USA,PG-13,225000000,2013,972,7.9,2.35,83000,33355354
24,Color,Chris Weitz,251,113,129,1000,Eva Green,16000,70083519,Adventure|Family|Fantasy,...,English,USA,PG-13,180000000,2007,6000,6.1,2.35,0,-109916481
25,Color,Peter Jackson,446,201,0,84,Thomas Kretschmann,6000,218051260,Action|Adventure|Drama|Romance,...,English,New Zealand,PG-13,207000000,2005,919,7.2,2.35,0,11051260
26,Color,James Cameron,315,194,0,794,Kate Winslet,29000,658672302,Drama|Romance,...,English,USA,PG-13,200000000,1997,14000,7.7,2.35,26000,458672302
27,Color,Anthony Russo,516,147,94,11000,Scarlett Johansson,21000,407197282,Action|Adventure|Sci-Fi,...,English,USA,PG-13,250000000,2016,19000,8.2,2.35,72000,157197282
28,Color,Peter Berg,377,131,532,627,Alexander Skarsgård,14000,65173160,Action|Adventure|Sci-Fi|Thriller,...,English,USA,PG-13,209000000,2012,10000,5.9,2.35,44000,-143826840
29,Color,Colin Trevorrow,644,124,365,1000,Judy Greer,3000,652177271,Action|Adventure|Sci-Fi|Thriller,...,English,USA,PG-13,150000000,2015,2000,7.0,2.00,150000,502177271
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5013,Color,Eric Eason,28,79,3,42,Panchito Gómez,93,NaN,Drama|Family,...,English,USA,NaN,24000,2002,46,7.0,1.78,61,NaN
5014,Color,Uwe Boll,58,80,892,492,Katharine Isabelle,986,NaN,Action|Crime|Thriller,...,English,Canada,R,NaN,2009,918,6.3,2.35,0,NaN
5015,Black and White,Richard Linklater,61,100,0,0,Richard Linklater,5,1227508,Comedy|Drama,...,English,USA,R,23000,1991,0,7.1,1.37,2000,1204508
5016,Color,Joseph Mazzella,NaN,90,0,9,Mikaal Bates,313,NaN,Crime|Drama|Thriller,...,English,USA,NaN,25000,2015,25,4.8,NaN,33,NaN
5017,Color,Travis Legge,1,90,138,138,Suzi Lorraine,370,NaN,Comedy|Romance,...,English,USA,NaN,22000,2013,184,3.3,1.78,200,NaN
5018,Color,Alex Kendrick,5,120,589,4,Lisa Arnold,51,NaN,Drama,...,English,USA,NaN,20000,2003,49,6.9,1.85,725,NaN
5019,Color,Marcus Nispel,43,91,158,265,Brittany Curran,630,NaN,Horror|Mystery|Thriller,...,English,USA,R,NaN,2015,512,4.6,1.85,0,NaN
5020,NaN,Brandon Landers,NaN,143,8,8,Alana Kaniewski,720,NaN,Drama|Horror|Thriller,...,English,USA,NaN,17350,2011,19,3.0,NaN,33,NaN
5021,Color,Jay Duplass,51,85,157,10,Katie Aselton,830,192467,Comedy|Drama|Romance,...,English,USA,R,15000,2005,224,6.6,NaN,297,177467
5022,Black and White,Jim Chuchu,6,60,0,4,Olwenya Maina,147,NaN,Drama,...,Swahili,Kenya,NaN,15000,2014,19,7.4,NaN,45,NaN
5023,Color,Daryl Wein,22,88,38,211,Heather Burns,331,76382,Romance,...,English,USA,NaN,15000,2009,212,6.2,2.35,324,61382
5024,Color,Jason Trost,42,78,91,86,Jason Trost,407,NaN,Sci-Fi|Thriller,...,English,USA,Unrated,20000,2011,91,4.0,2.35,835,NaN
5025,Color,John Waters,73,108,0,105,Mink Stole,462,180483,Comedy|Crime|Horror,...,English,USA,NC-17,10000,1972,143,6.1,1.37,0,170483
5026,Color,Olivier Assayas,81,110,107,45,Béatrice Dalle,576,136007,Drama|Music|Romance,...,French,France,R,4500,2004,133,6.9,2.35,171,131507
5027,Color,Jafar Panahi,64,90,397,0,Nargess Mamizadeh,5,673780,Drama,...,Persian,Iran,Not Rated,10000,2000,0,7.5,1.85,697,663780
5028,Black and White,Ivan Kavanagh,12,83,18,0,Michael Parle,10,NaN,Horror,...,English,Ireland,NaN,10000,2007,5,6.7,1.33,105,NaN
5029,Color,Kiyoshi Kurosawa,78,111,62,6,Anna Nakagawa,89,94596,Crime|Horror|Mystery|Thriller,...,Japanese,Japan,NaN,1000000,1997,13,7.4,1.85,817,-905404
5030,Color,Tadeo Garcia,NaN,84,5,12,Michael Cortez,21,NaN,Drama,...,English,USA,NaN,NaN,2004,20,6.1,NaN,22,NaN
5031,Color,Thomas L. Phillips,13,82,120,84,Joe Coffey,785,NaN,Comedy|Horror|Thriller,...,English,USA,NaN,200000,2012,98,5.4,16.00,424,NaN
5032,Color,Ash Baron-Cohen,10,98,3,152,Stanley B. Herman,789,NaN,Crime|Drama,...,English,USA,NaN,NaN,1995,194,6.4,NaN,20,NaN
5033,Color,Shane Carruth,143,77,291,8,David Sullivan,291,424760,Drama|Sci-Fi|Thriller,...,English,USA,PG-13,7000,2004,45,7.0,1.85,19000,417760
5034,Color,Neill Dela Llana,35,80,0,0,Edgar Tancangco,0,70071,Thriller,...,English,Philippines,Not Rated,7000,2005,0,6.3,NaN,74,63071
5035,Color,Robert Rodriguez,56,81,0,6,Peter Marquardt,121,2040920,Action|Crime|Drama|Romance|Thriller,...,Spanish,USA,R,7000,1992,20,6.9,1.37,0,2033920
5036,Color,Anthony Vallone,NaN,84,2,2,John Considine,45,NaN,Crime|Drama,...,English,USA,PG-13,3250,2005,44,7.8,NaN,4,NaN
5037,Color,Edward Burns,14,95,0,133,Caitlin FitzGerald,296,4584,Comedy|Drama,...,English,USA,Not Rated,9000,2011,205,6.4,NaN,413,-4416
5038,Color,Scott Smith,1,87,2,318,Daphne Zuniga,637,NaN,Comedy|Drama,...,English,Canada,NaN,NaN,2013,470,7.7,NaN,84,NaN
5039,Color,NaN,43,43,NaN,319,Valorie Curry,841,NaN,Crime|Drama|Mystery|Thriller,...,English,USA,TV-14,NaN,NaN,593,7.5,16.00,32000,NaN
5040,Color,Benjamin Roberds,13,76,0,0,Maxwell Moody,0,NaN,Drama|Horror|Thriller,...,English,USA,NaN,1400,2013,0,6.3,NaN,16,NaN
5041,Color,Daniel Hsia,14,100,0,489,Daniel Henney,946,10443,Comedy|Drama|Romance,...,English,USA,PG-13,NaN,2012,719,6.3,2.35,660,NaN
5042,Color,Jon Gunn,43,90,16,16,Brian Herzlinger,86,85222,Documentary,...,English,USA,PG,1100,2004,23,6.6,1.85,456,84122

In [22]:
data.profit.describe()

count    3.891000e+03
mean     5.844717e+06
std      2.261794e+08
min     -1.221330e+10
25%     -1.026518e+07
50%      8.516360e+05
75%      2.475147e+07
max      5.235058e+08
Name: profit, dtype: float64

In [23]:
data.loc[:,['gross','budget','profit']] #checking to see if it worked

          gross     budget     profit
0     760505847  237000000  523505847
1     309404152  300000000    9404152
2     200074175  245000000  -44925825
3     448130642  250000000  198130642
4           NaN        NaN        NaN
5      73058679  263700000 -190641321
6     336530303  258000000   78530303
7     200807262  260000000  -59192738
8     458991599  250000000  208991599
9     301956980  250000000   51956980
10    330249062  250000000   80249062
11    200069408  209000000   -8930592
12    168368427  200000000  -31631573
13    423032628  225000000  198032628
14     89289910  215000000 -125710090
15    291021565  225000000   66021565
16    141614023  225000000  -83385977
17    623279547  220000000  403279547
18    241063875  250000000   -8936125
19    179020854  225000000  -45979146
20    255108370  250000000    5108370
21    262030663  230000000   32030663
22    105219735  200000000  -94780265
23    258355354  225000000   33355354
24     70083519  180000000 -109916481
25    218051260  207000000   11051260
26    658672302  200000000  458672302
27    407197282  250000000  157197282
28     65173160  209000000 -143826840
29    652177271  150000000  502177271
...         ...        ...        ...
5013        NaN      24000        NaN
5014        NaN        NaN        NaN
5015    1227508      23000    1204508
5016        NaN      25000        NaN
5017        NaN      22000        NaN
5018        NaN      20000        NaN
5019        NaN        NaN        NaN
5020        NaN      17350        NaN
5021     192467      15000     177467
5022        NaN      15000        NaN
5023      76382      15000      61382
5024        NaN      20000        NaN
5025     180483      10000     170483
5026     136007       4500     131507
5027     673780      10000     663780
5028        NaN      10000        NaN
5029      94596    1000000    -905404
5030        NaN        NaN        NaN
5031        NaN     200000        NaN
5032        NaN        NaN        NaN
5033     424760       7000     417760
5034      70071       7000      63071
5035    2040920       7000    2033920
5036        NaN       3250        NaN
5037       4584       9000      -4416
5038        NaN        NaN        NaN
5039        NaN        NaN        NaN
5040        NaN       1400        NaN
5041      10443        NaN        NaN
5042      85222       1100      84122

[5043 rows x 3 columns]

In [24]:
monetary_data = data.loc[:,['gross','budget','profit']]  #lets just work with this for now

In [25]:
monetary_data.describe()

              gross        budget        profit
count  4.159000e+03  4.551000e+03  3.891000e+03
mean   4.846841e+07  3.975262e+07  5.844717e+06
std    6.845299e+07  2.061149e+08  2.261794e+08
min    1.620000e+02  2.180000e+02 -1.221330e+10
25%    5.340988e+06  6.000000e+06 -1.026518e+07
50%    2.551750e+07  2.000000e+07  8.516360e+05
75%    6.230944e+07  4.500000e+07  2.475147e+07
max    7.605058e+08  1.221550e+10  5.235058e+08

In [26]:
len(data) - len(monetary_data.dropna())  # curious how much data isnt being used if profit is what is being focused on

1152

In [27]:
monetary_data.sort(columns='profit', axis=0, ascending=False)

C:\Users\j_coo\Anaconda2\envs\ClassProject\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  """Entry point for launching an IPython kernel.

          gross     budget     profit
0     760505847  237000000  523505847
29    652177271  150000000  502177271
26    658672302  200000000  458672302
3024  460935665   11000000  449935665
3080  434949459   10500000  424449459
794   623279547  220000000  403279547
17    623279547  220000000  403279547
509   422783777   45000000  377783777
240   474544677  115000000  359544677
66    533316061  185000000  348316061
439   407999255   78000000  329999255
812   363024263   58000000  305024263
186   424645577  130000000  294645577
697   356784000   63000000  293784000
521   368049635   76000000  292049635
814   350123553   58800000  291323553
338   380838870   94000000  286838870
582   436471036  150000000  286471036
339   377019252   94000000  283019252
1536  309125409   32500000  276625409
836   329691196   55000000  274691196
2051  290158751   18000000  272158751
2601  285761243   18000000  267761243
236   380262555  113000000  267262555
161   403706375  139000000  264706375
563   336029560   74000000  262029560
1181  293501675   40000000  253501675
2917  260000000    8000000  252000000
125   400736600  150000000  250736600
519   323505540   75000000  248505540
...         ...        ...        ...
4994        NaN      50000        NaN
4995        NaN      42000        NaN
4996        NaN      45000        NaN
4999        NaN      75000        NaN
5000        NaN      40000        NaN
5001     321952        NaN        NaN
5002        NaN      50000        NaN
5003      24705        NaN        NaN
5005        NaN        NaN        NaN
5006        NaN      60000        NaN
5007       9609        NaN        NaN
5010        NaN        NaN        NaN
5013        NaN      24000        NaN
5014        NaN        NaN        NaN
5016        NaN      25000        NaN
5017        NaN      22000        NaN
5018        NaN      20000        NaN
5019        NaN        NaN        NaN
5020        NaN      17350        NaN
5022        NaN      15000        NaN
5024        NaN      20000        NaN
5028        NaN      10000        NaN
5030        NaN        NaN        NaN
5031        NaN     200000        NaN
5032        NaN        NaN        NaN
5036        NaN       3250        NaN
5038        NaN        NaN        NaN
5039        NaN        NaN        NaN
5040        NaN       1400        NaN
5041      10443        NaN        NaN

[5043 rows x 3 columns]

In [28]:
data[data.profit > 0].director_name

0            James Cameron
1           Gore Verbinski
3        Christopher Nolan
6                Sam Raimi
8              Joss Whedon
9              David Yates
10             Zack Snyder
13          Gore Verbinski
15             Zack Snyder
17             Joss Whedon
20           Peter Jackson
21               Marc Webb
23           Peter Jackson
25           Peter Jackson
26           James Cameron
27           Anthony Russo
29         Colin Trevorrow
30              Sam Mendes
31               Sam Raimi
32             Shane Black
33              Tim Burton
34            Brett Ratner
35             Dan Scanlon
36             Michael Bay
37             Michael Bay
38               Sam Raimi
39               Marc Webb
40         Joseph Kosinski
43             Lee Unkrich
45               James Wan
               ...
4931           John Carney
4936           Tobe Hooper
4941         Michael Moore
4947          Lynn Shelton
4955         Alex Kendrick
4956          Travis Cluff
4958     Harry F. Millarde
4959       Robert Townsend
4962         Larry Blamire
4971        Dennis Iliadis
4973      Darren Aronofsky
4975       Myles Berkowitz
4977       Morgan Spurlock
4984          Edward Burns
4987           Lena Dunham
4997    David Gordon Green
4998          Kevin Jordan
5004            Mike Bruce
5008           Kevin Smith
5011           Neil LaBute
5015     Richard Linklater
5021           Jay Duplass
5023            Daryl Wein
5025           John Waters
5026       Olivier Assayas
5027          Jafar Panahi
5033         Shane Carruth
5034      Neill Dela Llana
5035      Robert Rodriguez
5042              Jon Gunn
Name: director_name, dtype: object

In [29]:
 data.loc[:,['profit','director_name']].sort(columns='profit', axis=0, ascending=False).dropna()  #Most profit attached to director

C:\Users\j_coo\Anaconda2\envs\ClassProject\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  """Entry point for launching an IPython kernel.

           profit        director_name
0       523505847        James Cameron
29      502177271      Colin Trevorrow
26      458672302        James Cameron
3024    449935665         George Lucas
3080    424449459     Steven Spielberg
794     403279547          Joss Whedon
17      403279547          Joss Whedon
509     377783777         Roger Allers
240     359544677         George Lucas
66      348316061    Christopher Nolan
439     329999255            Gary Ross
812     305024263           Tim Miller
186     294645577     Francis Lawrence
697     293784000     Steven Spielberg
521     292049635        Pierre Coffin
814     291323553       Clint Eastwood
338     286838870       Andrew Stanton
582     286471036       Andrew Adamson
339     283019252        Peter Jackson
1536    276625409     Richard Marquand
836     274691196      Robert Zemeckis
2051    272158751       Irvin Kershner
2601    267761243       Chris Columbus
236     267262555         George Lucas
161     264706375            Sam Raimi
563     262029560           Kyle Balda
1181    253501675   M. Night Shyamalan
2917    252000000     Steven Spielberg
125     250736600           Chris Buck
519     248505540        Yarrow Cheney
...           ...                  ...
3879   -115035182           Joe Wright
145    -115035182           Joe Wright
303    -115035182           Joe Wright
113    -120706229         Oliver Stone
14     -125710090       Gore Verbinski
143    -128620685          Simon Wells
62     -128624673       Lana Wachowski
49     -129828140         Bryan Singer
85     -136702695          Carl Rinsch
2339   -139853928     Jean-Marie Poiré
28     -143826840           Peter Berg
1782   -149237822       Jacques Perrin
3877   -149800772             R. Balki
91     -164334574      Robert Zemeckis
3659   -188094481      Prachya Pinkaew
5      -190641321       Andrew Stanton
2740   -299897945             Tony Jaa
1016   -375868702           Luc Besson
3311   -399545745  Chatrichalerm Yukol
1338   -553005191             John Woo
3273   -598397534          Anurag Basu
3075   -696724557          Karan Johar
3851   -698312689         Carlos Saura
4542   -989962610        Takao Okawara
3423  -1099560838      Katsuhiro Ôtomo
2334  -2127109510      Katsuhiro Ôtomo
2323  -2397701809       Hayao Miyazaki
3005  -2499804112         Lajos Koltai
3859  -4199788333       Chan-wook Park
2988 -12213298588         Joon-ho Bong

[3891 rows x 2 columns]

d

In [32]:
director_datapos = data[data.profit > 0]
director_datamostprofit = director_datapos.loc[:,['profit','director_name']].sort(columns='profit', axis=0, ascending=False)
director_datamostprofit
# directors that have made a profit  learning how to use exceptions

C:\Users\j_coo\Anaconda2\envs\ClassProject\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)

         profit       director_name
0     523505847       James Cameron
29    502177271     Colin Trevorrow
26    458672302       James Cameron
3024  449935665        George Lucas
3080  424449459    Steven Spielberg
794   403279547         Joss Whedon
17    403279547         Joss Whedon
509   377783777        Roger Allers
240   359544677        George Lucas
66    348316061   Christopher Nolan
439   329999255           Gary Ross
812   305024263          Tim Miller
186   294645577    Francis Lawrence
697   293784000    Steven Spielberg
521   292049635       Pierre Coffin
814   291323553      Clint Eastwood
338   286838870      Andrew Stanton
582   286471036      Andrew Adamson
339   283019252       Peter Jackson
1536  276625409    Richard Marquand
836   274691196     Robert Zemeckis
2051  272158751      Irvin Kershner
2601  267761243      Chris Columbus
236   267262555        George Lucas
161   264706375           Sam Raimi
563   262029560          Kyle Balda
1181  253501675  M. Night Shyamalan
2917  252000000    Steven Spielberg
125   250736600          Chris Buck
519   248505540       Yarrow Cheney
...         ...                 ...
986      203020       Beeban Kidron
4662     201437        Victor Nunez
324      200000         David Mamet
4997     199816  David Gordon Green
4899     181225    Maurizio Benazzo
5021     177467         Jay Duplass
5025     170483         John Waters
3504     165429       Phillip Noyce
971      150619  Jorge R. Gutiérrez
5026     131507     Olivier Assayas
824      128566  Paul W.S. Anderson
4860     124220     Vincenzo Natali
297      117603      Gary Trousdale
4108     105269       Enrique Begne
4740     103943   Jacob Aaron Estes
2681     100000      Mark L. Lester
5042      84122            Jon Gunn
59        80850        Brett Ratner
4962      70536       Larry Blamire
5034      63071    Neill Dela Llana
5023      61382          Daryl Wein
4642      57962         David Slade
3550      57096    Denis Villeneuve
4851      48622         Craig Zobel
3922      46737    Steven Shainberg
4863      41309       Greg Harrison
4800      25899          Ray Griggs
4904      15185       Justin Dillon
3768       9677        Duncan Jones
973        7168      Clint Eastwood

[2050 rows x 2 columns]

In [31]:
director_datamostprofit.sort(columns='director_name', axis=0, ascending=False)

C:\Users\j_coo\Anaconda2\envs\ClassProject\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  """Entry point for launching an IPython kernel.

         profit          director_name
3678    1239558       Émile Gaudreault
4401   32885635            Zack Snyder
1759   32885635            Zack Snyder
10     80249062            Zack Snyder
709   145592590            Zack Snyder
15     66021565            Zack Snyder
4189   24281723             Zach Braff
4478    2406383         Youssef Delara
519   248505540          Yarrow Cheney
2481   15687528            Xavier Gens
2560    7713577            Woody Allen
3907    6515579            Woody Allen
2664    8089926            Woody Allen
3889   35200000            Woody Allen
1627   39816662            Woody Allen
2415   15404871            Woody Allen
221    42618434      Wolfgang Petersen
957    17823573      Wolfgang Petersen
399    87620724      Wolfgang Petersen
4238   21550000          William Wyler
1631   27410049        William Shatner
2364   21846082         William Malone
2916  196565000       William Friedkin
4449  182925485       William Cottrell
2231   14078294     William Brent Bell
4545   52245055     William Brent Bell
3112   25794166     William Brent Bell
672    20911262             Will Gluck
1426   20802754             Will Gluck
3389   50401464             Will Gluck
...         ...                    ...
4267    3383834  Alejandro G. Iñárritu
2204    9300771  Alejandro G. Iñárritu
2414   24335698  Alejandro G. Iñárritu
2485   79471845     Alejandro Amenábar
1241   12320979      Alejandro Agresti
3988   24400000          Albert Hughes
463    14822707          Albert Hughes
127    36360018            Alan Taylor
1442    2481242              Alan Poul
1079   55768056         Alan J. Pakula
2791    1062898              Alan Cohn
4402   17067631        Adrienne Shelly
967     2752475            Adrian Lyne
2763  142645693            Adrian Lyne
3467   90900000            Adrian Lyne
1760   25400856          Adam Shankman
456    29993847          Adam Shankman
2157   99541238          Adam Shankman
834    57006880          Adam Shankman
3037   30227069          Adam Shankman
729    22569532          Adam Shankman
531    43823091          Adam Shankman
294    19219978             Adam McKay
571    75213377             Adam McKay
1902   58136909             Adam McKay
1756   42235322             Adam McKay
660    35468793             Adam McKay
4070   13435068            Adam Marcus
2182   28546578          Aaron Seltzer
3497    1676553        Aaron Schneider

[2050 rows x 2 columns]

In [56]:
director_data = data.loc[:,['profit','director_name']].sort(columns='profit', axis=0, ascending=False).dropna()
# director_datasum = director_data.groupby('director_name').sum() first attempt
director_datasum = director_data
director_datasum['profit_sum'] = director_datasum.groupby('director_name')['profit'].transform(sum)
director_df_profit_organized = director_datasum.loc[:,['profit_sum','director_name']].sort(columns='profit_sum', axis=0, ascending=False).drop_duplicates('director_name').head(40)
director_df_profit_organized
# Ranking of directors fom most profitable to least profitable. 
# possible questions not answered yet that need to be looked into:
# Are they becoming more or less profitable?
# Was this profit from a singular movie while most others were failures?
# Most profit does not necessarily mean higher rate of return on investment, could be that a lesser individual on the list gives
#              a better percentage return on investment
#consistent successes from inconsistent successes.

C:\Users\j_coo\Anaconda2\envs\ClassProject\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  """Entry point for launching an IPython kernel.
C:\Users\j_coo\Anaconda2\envs\ClassProject\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  """

      profit_sum            director_name
589   2486332231         Steven Spielberg
240   1386641480             George Lucas
291   1199625910            James Cameron
794   1000886628              Joss Whedon
385    941707624           Chris Columbus
2049   900969279            Peter Jackson
134    824275480               Tim Burton
96     808227576        Christopher Nolan
682    769381547              Jon Favreau
207    755501971         Francis Lawrence
528    644242537              Michael Bay
1784   642524555                Jay Roach
993    618949198                Sam Raimi
1245   610221100           Clint Eastwood
662    581756030            Todd Phillips
375    549309108          Robert Zemeckis
16     522446920           Andrew Adamson
3696   514276204                James Wan
29     505435063          Colin Trevorrow
583    475915953            John Lasseter
521    474551280            Pierre Coffin
67     474341341              Pete Docter
939    460690377                Phil Lord
581    444596768       M. Night Shyamalan
2245   416336386           Garry Marshall
74     413339768              Tom Shadyac
400    407529636        Steven Soderbergh
823    394762263               Shawn Levy
942    378105992  Rawson Marshall Thurber
509    377087335             Roger Allers
508    370891801               Ron Howard
1876   355295035              Bill Condon
1612   348753811            Jason Reitman
2922   345701230                Tim Story
1586   341781972             Dennis Dugan
1010   333536667                Gary Ross
2930   323939594        Quentin Tarantino
812    305024263               Tim Miller
209    304057871          Carlos Saldanha
2262   301277574      Catherine Hardwicke